name: 'GitHub Actions Pinner'
description: 'Validate GitHub Actions to ensure they use specific commit SHAs for improved security'
author: 'gha-pinner'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  target:
    description: 'File or directory to validate actions in'
    required: true
    default: '.github/workflows'
  target-type:
    description: 'Type of target (file or dir)'
    required: false
    default: 'dir'
    enum: ['file', 'dir']

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install gha-pinner
      shell: bash
      run: |
        pip install ${{ github.action_path }}

    - name: Generate suggestions
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        gha-pinner ${{ inputs.target-type }} "${{ inputs.target }}"

    - name: Suggest fixes on the PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: gha-pinner
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
