name: Pin Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 

jobs:
  pin-actions:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Validate GitHub Actions
        uses: sapasapasapa/gha-pinner@v1.0.0
        with:
          target: '.github/workflows'
          target-type: 'dir'
          create-pr: true
